/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents;

import Other.Company;
import UIComponents.PayBills;
import UIComponents.PaymentPortal;
import bill.ElecBill;
import static javafx.application.Platform.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author Raghav
 */
public class DeleteCompany extends javax.swing.JFrame {
     
     String billid;
    
    /**
     * Creates new form PayElecBill
     */
    public DeleteCompany() {
        initComponents();
        hideLabel();
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        billIDTF = new javax.swing.JTextField();
        fetchBT = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        compid = new javax.swing.JLabel();
        compName = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        regOff = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        backToMainMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("DELETE COMPANY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("COMPANY ID");

        fetchBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fetchBT.setText("SUBMIT");
        fetchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchBTActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setText("COMPANY ID");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setText("COMPANY NAME");

        compid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compid.setText("BILL ID :");

        compName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compName.setText("BILL ID :");

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setText("EMAIL");

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("BILL ID :");

        gst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gst.setText("BILL ID :");

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl4.setText("GST NUMBER");

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        regOff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regOff.setText("BILL ID :");

        lbl8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl8.setText("REGISTERED OFFICE");

        backToMainMenuBtn.setText("Back To Main Menu");
        backToMainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToMainMenuBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(53, 53, 53)
                                .addComponent(billIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl3)
                                    .addComponent(lbl8)
                                    .addComponent(lbl1)
                                    .addComponent(lbl2)
                                    .addComponent(lbl4))
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gst)
                                    .addComponent(compName)
                                    .addComponent(compid)
                                    .addComponent(regOff)
                                    .addComponent(email))))))
                .addGap(192, 241, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(delete)
                        .addGap(393, 393, 393))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fetchBT)
                .addGap(374, 374, 374))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToMainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(fetchBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(compid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(compName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(regOff))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(email))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gst)
                    .addComponent(lbl4))
                .addGap(43, 43, 43)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchBTActionPerformed
        // TODO add your handling code here:
    
       Company c=  new Company();
       String id = billIDTF.getText();
         
        
        c=c.searchFromDB(id);
        
       
 
        if(id.equals(c.getId()))
        { 
        JOptionPane.showMessageDialog(this,"BILL FETCHED SUCCESSFULLY"); 
       
        email.setText(c.getEmail());
        compid.setText(c.getId());
        compName.setText(c.getName());
        gst.setText(c.getGstNo());
        regOff.setText(c.getRegOff());        
        showLabel();          
        }
        else
            JOptionPane.showMessageDialog(this,"WRONG ID..TRY AGAIN"); 

    }//GEN-LAST:event_fetchBTActionPerformed

    private void backToMainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
                new PayBills().setVisible(true);
            }
        });
    }//GEN-LAST:event_backToMainMenuBtnActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Company c=  new Company();
       String id = billIDTF.getText();
         
        
        boolean i=c.deleteFromDB(id);
        if(i==false)
        { 
        JOptionPane.showMessageDialog(this,"ENTRY DELETED SUCCESSFULLY");          
        }
        else
            JOptionPane.showMessageDialog(this,"DELETION UNSUCCESSFUL"); 
        
             
    }//GEN-LAST:event_deleteActionPerformed

    public String getValue()
    {
        return billid;
    }
    public void setValue(String billid)
    {
        this.billid=billid;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainMenuBtn;
    private javax.swing.JTextField billIDTF;
    private javax.swing.JLabel compName;
    private javax.swing.JLabel compid;
    private javax.swing.JButton delete;
    private javax.swing.JLabel email;
    private javax.swing.JButton fetchBT;
    private javax.swing.JLabel gst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel regOff;
    // End of variables declaration//GEN-END:variables

    private void hideLabel() {
         //To change body of generated methods, choose Tools | Templates.
        email.setVisible(false);
        compid.setVisible(false);
        compName.setVisible(false);
     
       
        gst.setVisible(false);
        regOff.setVisible(false);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
       
        lbl8.setVisible(false);
        
        delete.setVisible(false);
    }

    private void showLabel() {
        //To change body of generated methods, choose Tools | Templates.
        email.setVisible(true);
       
        compid.setVisible(true);
        compName.setVisible(true);
       
        gst.setVisible(true);
        regOff.setVisible(true);
        lbl1.setVisible(true);
        lbl2.setVisible(true);
        lbl3.setVisible(true);
        lbl4.setVisible(true);
        
        lbl8.setVisible(true);
        
        delete.setVisible(true);
    }
}
