/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents;

import Other.Customer;
import Other.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author Reshma
 */
public class UpdateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCustomer
     */
    public UpdateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        updateIDLabel = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();
        updateIdtf = new javax.swing.JTextField();
        backToMain = new javax.swing.JButton();
        updateNameLabel = new javax.swing.JLabel();
        updateNametf = new javax.swing.JTextField();
        updateEmailLabel = new javax.swing.JLabel();
        updateEmailtf = new javax.swing.JTextField();
        updatePhnLabel = new javax.swing.JLabel();
        updatePhntf = new javax.swing.JTextField();
        updatePwdLabel = new javax.swing.JLabel();
        updatePwdtf = new javax.swing.JTextField();
        updatePwdLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateAddTF = new javax.swing.JTextArea();
        submitID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Update Customer");

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        updateIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateIDLabel.setText("USERNAME");

        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        updateIdtf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateIdtf.setText("Enter ID to update details");

        backToMain.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backToMain.setText("BACK TO ADMIN MENU");
        backToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainActionPerformed(evt);
            }
        });

        updateNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateNameLabel.setText("NAME");

        updateNametf.setEditable(false);
        updateNametf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        updateEmailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateEmailLabel.setText("EMAIL");

        updateEmailtf.setEditable(false);
        updateEmailtf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        updatePhnLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatePhnLabel.setText("MOBILE NO.");

        updatePhntf.setEditable(false);
        updatePhntf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        updatePwdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatePwdLabel.setText("PASSWORD");

        updatePwdtf.setEditable(false);

        updatePwdLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatePwdLabel2.setText("ADDRESS");

        updateAddTF.setEditable(false);
        updateAddTF.setColumns(20);
        updateAddTF.setRows(5);
        jScrollPane1.setViewportView(updateAddTF);

        submitID.setText("Submit");
        submitID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(backToMain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updatePhnLabel)
                                    .addComponent(updateNameLabel)
                                    .addComponent(updateEmailLabel))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateEmailtf)
                                    .addComponent(updateIdtf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(updateNametf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(updatePhntf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addComponent(submitID))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(updatePwdLabel2)
                                    .addGap(37, 37, 37)
                                    .addComponent(jScrollPane1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(updatePwdLabel)
                                    .addGap(24, 24, 24)
                                    .addComponent(updatePwdtf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(updatebtn)
                                        .addGap(125, 125, 125)))))))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 229, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(updateIDLabel)
                    .addContainerGap(554, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNameLabel)
                    .addComponent(updateNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePhnLabel)
                    .addComponent(updatePhntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updatePwdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePwdLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePwdLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn)
                    .addComponent(clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(backToMain)
                .addGap(51, 51, 51))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(updateIDLabel)
                    .addContainerGap(687, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        Customer cusObj = new Customer();
        
        cusObj.setID(updateIdtf.getText());
        cusObj.setName(updateNametf.getText());
        cusObj.setPhn(updatePhntf.getText());
        cusObj.setEmail(updateEmailtf.getText());
        cusObj.setAddr(updateAddTF.getText());
        cusObj.setPassword(updatePwdtf.getText());
        //cusObj.setU(updateUsernameTF.getText());
        int r = cusObj.updateDB(cusObj);
        if(r==0){
            JOptionPane.showMessageDialog(this,"SOMETHING WENT WRONG");

        }
        else{
            JOptionPane.showMessageDialog(this,"SUCCESSFULLY UPDATED ");
        }
        updateIdtf.setText("");
        updateNametf.setText("");
        updatePhntf.setText("");
        updateEmailtf.setText("");
        updatePwdtf.setText("");
    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        updateIdtf.setText("");
        updateNametf.setText("");
        updatePhntf.setText("");
        updateEmailtf.setText("");
        updatePwdtf.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void backToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
                new AdminFrontPortal().setVisible(true);
            }
        });
    }//GEN-LAST:event_backToMainActionPerformed

    private void submitIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitIDActionPerformed
        // TODO add your handling code here:
        //updateIdtf.setEditable(false);
        updateEmailtf.setEditable(true);
        updatePhntf.setEditable(true);
        updatePwdtf.setEditable(true);
        updateNametf.setEditable(true);
        updateIdtf.setEditable(false);
        
        Customer cusObj = new Customer();
        
        cusObj=cusObj.searchFromDB(updateIdtf.getText());
     
                
        if(cusObj.getName()==null)
        {
        JOptionPane.showMessageDialog(this,"INVALID ID ");
        }
        else
        {
        updateNametf.setText(cusObj.getName());
        updateEmailtf.setText(cusObj.getEmail());
        updatePhntf.setText(cusObj.getPhn());
        updateAddTF.setText(cusObj.getAddr());
        updatePwdtf.setText(cusObj.getPassword());
        }
//        String id = updateIdtf.getText();
//        c= Customer.searchByID(id);
//        
//        System.out.println(c.getName());
//        
//        updateNametf.setText(c.getName());
//        updatePhntf.setText(c.getPhn());
//        updateEmailtf.setText(c.getEmail());
    }//GEN-LAST:event_submitIDActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMain;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitID;
    private javax.swing.JTextArea updateAddTF;
    private javax.swing.JLabel updateEmailLabel;
    private javax.swing.JTextField updateEmailtf;
    private javax.swing.JLabel updateIDLabel;
    private javax.swing.JTextField updateIdtf;
    private javax.swing.JLabel updateNameLabel;
    private javax.swing.JTextField updateNametf;
    private javax.swing.JLabel updatePhnLabel;
    private javax.swing.JTextField updatePhntf;
    private javax.swing.JLabel updatePwdLabel;
    private javax.swing.JLabel updatePwdLabel2;
    private javax.swing.JTextField updatePwdtf;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
